import * as G from './engine.mjs?v=2';
const $=id=>document.getElementById(id);let cafe=null,s=null,high=true,muted=false,ac=null,hum=null,volume=null;
function audio(kind){if(muted)return;try{ac??=new(window.AudioContext||window.webkitAudioContext)();ac.resume();const o=ac.createOscillator(),v=ac.createGain();o.type='triangle';o.frequency.value=kind==='serve'?740:kind==='grind'?95:280;v.gain.setValueAtTime(.06,ac.currentTime);v.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+.25);o.connect(v).connect(ac.destination);o.start();o.stop(ac.currentTime+.3);}catch{}}
function pump(on){if(!ac||muted)on=false;if(on&&!hum){hum=ac.createOscillator();volume=ac.createGain();hum.type='sawtooth';hum.frequency.value=68;volume.gain.value=.018;hum.connect(volume).connect(ac.destination);hum.start();}if(!on&&hum){hum.stop();hum.disconnect();hum=null;}}
function modal(title,body,buttons){$('modalTitle').textContent=title;$('modalBody').textContent=body;$('modalActions').replaceChildren();for(const[label,fn]of buttons){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('modal').close();fn();};$('modalActions').append(b);}if(!$('modal').open)$('modal').showModal();cafe?.sync(s,false);pump(false);}
function render(){if(!s)return;$('chapter').textContent='SHIFT '+Math.min(3,Math.floor(s.index/3)+1)+' / PESANAN '+Math.min(9,s.index+1)+'/9';$('order').textContent=G.order(s);$('recipe').textContent='Espresso + '+(G.order(s)==='Americano'?'air panas':'susu');$('patience').value=s.patience;$('time').textContent=Math.ceil(s.patience)+' detik kesabaran';$('score').textContent='Rp'+s.cash.toLocaleString('id-ID');$('health').textContent=s.served+' tersaji · '+s.missed+'/3 pelanggan pergi';$('cup').textContent=!s.cup?'Tangan kosong':s.cup.addition?'Minuman siap':s.cup.espresso?'Espresso siap':s.cup.tamped?'Kopi sudah dipadatkan':s.cup.ground?'Kopi giling siap':'Gelas kosong di tangan';$('machine').textContent=s.dirty?'MESIN PERLU DICUCI':'MESIN BERSIH';$('hint').textContent=G.hint(s);$('notice').textContent=s.message;$('extraction').hidden=s.job?.type!=='brew';$('needle').style.left=Math.min(100,s.brew/12*100)+'%';$('brewTime').textContent=s.brew.toFixed(1)+' detik';const st=cafe?.nearest();$('aim').textContent=st?st.name:'Dekati stasiun di sepanjang bar';$('interact').disabled=!st;}
function start(){s=G.fresh();cafe.start();$('intro').hidden=true;$('hud').hidden=false;$('pause').hidden=false;audio('start');render();}
function menu(){s=null;cafe.menu();pump(false);$('intro').hidden=false;$('hud').hidden=true;$('pause').hidden=true;}
function interact(){if(!s||s.status!=='playing'||$('modal').open)return;const st=cafe.nearest();if(!st)return;const n=s.served;G.act(s,st.id);audio(st.id);if(s.served>n){cafe.serve();audio('serve');}render();finish();}
function finish(){if(s&&s.status!=='playing'&&!$('modal').open)modal(s.status==='won'?'Shift selesai. Kerja bagus!':'Shift berakhir.',s.served+' dari 9 pesanan tersaji. Pendapatan Rp'+s.cash.toLocaleString('id-ID')+'. Pelanggan pergi: '+s.missed+'.',[['Coba lagi',start],['Menu utama',menu]]);}
function pause(){if(s?.status==='playing')modal('Istirahat sejenak','Waktu dan proses ekstraksi berhenti selama jeda.',[['Lanjutkan',()=>{}],['Menu utama',menu]]);}
$('start').onclick=start;$('pause').onclick=pause;$('interact').onclick=interact;
$('help').onclick=()=>modal('Di balik meja bar','WASD: berjalan. Seret area 3D: melihat sekitar. E: gunakan stasiun terdekat (tidak harus tepat membidik). Tombol bawah tersedia untuk sentuh.\n\n1. Ambil gelas.\n2. Giling kopi (2 detik).\n3. Tekan mesin: padatkan, lalu tekan lagi untuk menyeduh.\n4. Hentikan mesin pada 4–7 detik untuk tip terbaik.\n5. Tambahkan susu atau air (2,5 detik).\n6. Serahkan di terminal. Cuci mesin sebelum pesanan berikutnya.\n\nBak cuci membuang racikan di tangan. Tiga pelanggan pergi mengakhiri sesi. Angka waktu adalah penyederhanaan game.',[['Mengerti',()=>{}]]);
$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Suara mati':'Suara aktif';if(muted)pump(false);else audio('start');};$('quality').onclick=()=>{high=!high;cafe?.quality(high);$('quality').textContent=high?'Grafik tinggi':'Grafik hemat';};
window.addEventListener('keydown',e=>{if(e.repeat||$('modal').open)return;if(e.code==='KeyE')interact();if(e.code==='KeyP')pause();});
$('lookLeft').onclick=()=>cafe?.look(.25);$('lookRight').onclick=()=>cafe?.look(-.25);
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);cafe?.key(b.dataset.key,true);};b.onpointerup=b.onpointercancel=()=>cafe?.key(b.dataset.key,false);});
$('modal').addEventListener('cancel',e=>{if(s&&s.status!=='playing')e.preventDefault();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&s?.status==='playing')pause();});window.addEventListener('blur',()=>{if(s?.status==='playing'&&!$('modal').open)pause();});
window.addEventListener('cafe-context-lost',()=>modal('Grafik terhenti','WebGL terputus. Muat ulang halaman untuk memulihkan kafe.',[['Muat ulang',()=>location.reload()]]));
let last=performance.now();setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.2);last=now;const running=!!s&&s.status==='playing'&&!$('modal').open&&!document.hidden;cafe?.sync(s,running);pump(running&&!!s.job);if(running){G.tick(s,dt);render();finish();}},50);
try{const{createCafe}=await import('./scene.js?v=2');cafe=createCafe($('scene'),G.stations);$('start').disabled=false;$('loading').textContent='Kafe siap · Optimalkan di komputer, layar lebar.';}catch(e){$('loading').textContent='3D gagal dimuat. Periksa internet/CDN, WebGL2, lalu muat ulang.';console.error(e);}
