import * as G from './engine.mjs';
const $=id=>document.getElementById(id);let cafe=null,s=null,high=true;
const format=n=>'Rp'+n.toLocaleString('id-ID');
function modal(tag,title,body,buttons){$('modalTag').textContent=tag;$('modalTitle').textContent=title;$('modalBody').textContent=body;$('modalButtons').replaceChildren();buttons.forEach(([label,fn])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('modal').close();fn();};$('modalButtons').append(b);});if(!$('modal').open)$('modal').showModal();}
function render(){if(!s)return;const order=G.order(s);$('shiftName').textContent=G.shifts[s.shift].name;$('score').textContent=format(s.cash)+' · '+s.served+' pesanan';$('orderNumber').textContent=`${s.index+1}/${G.shifts[s.shift].orders.length}`;$('orderName').textContent=order.name;$('recipe').textContent=order.items.map(i=>G.ingredients[i]).join(' + ');$('mix').textContent=s.mix.length?s.mix.map(i=>G.ingredients[i]).join(' + '):'Gelas kosong';$('timeBar').style.transform=`scaleX(${s.left/G.shifts[s.shift].seconds})`;$('timeText').textContent=`Kesabaran pelanggan: ${Math.ceil(s.left)} detik`;cafe?.mix(s.mix.length);}
function start(){s=G.fresh();$('intro').hidden=true;$('hud').hidden=false;$('pause').hidden=false;$('notice').textContent='Pilih bahan sesuai resep, lalu sajikan.';render();}
function menu(){s=null;$('intro').hidden=false;$('hud').hidden=true;$('pause').hidden=true;}
for(const [id,name]of Object.entries(G.ingredients)){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{if(G.add(s,id)){$('notice').textContent=name+' ditambahkan.';render();}else $('notice').textContent='Maksimal 4 bahan. Kosongkan jika racikan salah.';};$('ingredients').append(b);}
$('start').onclick=start;$('quality').onclick=()=>{high=!high;cafe?.quality(high);$('quality').textContent='Grafik: '+(high?'tinggi':'hemat');};$('camera').onclick=()=>cafe?.rotate();
$('clear').onclick=()=>{if(s?.status==='playing'){s.mix=[];render();$('notice').textContent='Racikan dikosongkan. Waktu tetap berjalan.';}};
$('serve').onclick=()=>{if(!s)return;const success=G.serve(s);$('notice').textContent=success?'Pesanan cocok! Pendapatan bertambah.':'Resep belum cocok. Racikan dikosongkan, coba lagi.';if(success)cafe?.serve();render();check();};
function check(){if(s.status==='complete')modal('SHIFT SELESAI','Nice work, barista.',`Pendapatan ${format(s.cash)}. Shift selanjutnya membawa resep baru.`,[['Lanjut shift',()=>{G.next(s);render();}],['Menu utama',menu]]);if(s.status==='won'){let best=0;try{best=Math.max(Number(localStorage.getItem('bit-bean-best'))||0,s.cash);localStorage.setItem('bit-bean-best',String(best));}catch{}modal('KAFE TUTUP','A day well brewed.',`${s.served} pesanan tersaji. Pendapatan ${format(s.cash)}. Percobaan resep salah: ${s.mistakes}.\nTerima kasih sudah meramaikan Bit & Bean!`,[['Main lagi',start],['Menu utama',menu]]);}if(s.status==='lost')modal('WAKTU HABIS','Pelanggan harus pergi.',`Pendapatan sesi ini ${format(s.cash)}. Coba lagi dan perhatikan resep pada tiket.`,[['Ulang dari awal',start],['Menu utama',menu]]);}
$('pause').onclick=()=>{if(s?.status==='playing')modal('JEDA','Take a coffee break.', 'Waktu berhenti selama dialog ini terbuka.',[['Lanjutkan',()=>{}],['Menu utama',menu]]);};
$('help').onclick=()=>modal('PANDUAN','Your first shift.', '1. Baca resep pada tiket pesanan.\n2. Klik bahan tepat satu kali sesuai resep. Urutan bebas, jumlah harus sama.\n3. Klik Sajikan sebelum waktu habis.\n4. Selesaikan 3 shift dan 12 pesanan.\n\nKosongkan racikan jika keliru. Timer berhenti saat jeda atau tab tidak aktif. Kamera dapat diputar melalui tombol di atas.',[['Mengerti',()=>{}]]);
$('modal').addEventListener('cancel',e=>{if(s&&s.status!=='playing')e.preventDefault();});
let last=performance.now();setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.5);last=now;if(!s||s.status!=='playing'||$('modal').open||document.hidden)return;G.tick(s,dt);render();check();},100);
window.addEventListener('cafe-context-lost',()=>{if(s)s.status='lost';modal('GRAFIK TERHENTI','Koneksi GPU terputus.','Muat ulang halaman untuk memulihkan tampilan 3D.',[['Muat ulang',()=>location.reload()]]);});
try{const {createCafe}=await import('./scene.js');cafe=createCafe($('scene'));$('loading').textContent='Kafe siap. Selamat datang di golden hour.';$('start').disabled=false;}catch(error){$('loading').textContent='Tampilan 3D belum dapat dimuat. Pastikan internet aktif, WebGL tersedia, dan CDN jsDelivr tidak diblokir. Muat ulang halaman untuk mencoba lagi.';console.error('Cafe 3D initialization failed:',error);}
